server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:slipnote.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=slipnote
server.http.strict-transport-security.max-age=31536000
server.http.strict-transport-security.include-sub-domains=true
spring.application.name=SlipNote
spring.datasource.url=jdbc:postgresql://localhost:5432/app_db
spring.datasource.username=slipnote
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.redis.host=localhost
spring.data.redis.port=6379
